# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-cross_origin', '~> 0.3.1'

gem 'dotenv', '~> 2.7'

gem 'mx-platform-ruby'

group :test do
  # Test it with RSpec (BDD for Ruby)
  gem 'rspec-core'
end

gem 'rack', '>= 2.2.6.3'

gem 'httparty', '~> 0.20.0'

gem 'colorize', '~> 0.8.1'
