source 'https://rubygems.org'

gem 'sinatra'
gem "sinatra-cross_origin", "~> 0.3.1"

gem "dotenv", "~> 2.7"

gem 'mx-platform-ruby'

group :test do
  # Test it with RSpec (BDD for Ruby)
  gem 'rspec-core'

  # Keep files consistent
  gem 'rubocop', require: false
end
