version: "3.7"

services:
  ruby:
    image: mx-quickstart-ruby
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    env_file: .env
    ports:
      - 8000:8000
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
